"""remove service_name from service_request

Revision ID: ca30059b06f4
Revises: fbd4d72b2043
Create Date: 2026-07-15 18:02:14.723007

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'ca30059b06f4'
down_revision = 'fbd4d72b2043'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('service_request', schema=None) as batch_op:
        batch_op.drop_column('service_name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('service_request', schema=None) as batch_op:
        batch_op.add_column(sa.Column('service_name', mysql.VARCHAR(length=100), nullable=False))

    # ### end Alembic commands ###
