"""add service_name service_request

Revision ID: fbd4d72b2043
Revises: 
Create Date: 2026-07-15 17:04:54.550955

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fbd4d72b2043'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('service_request', schema=None) as batch_op:
        batch_op.add_column(sa.Column('service_name', sa.String(length=100), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('service_request', schema=None) as batch_op:
        batch_op.drop_column('service_name')

    # ### end Alembic commands ###
